# Generated by Django 3.1 on 2020-09-11 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_auto_20200911_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staging',
            name='notice_period',
            field=models.TextField(null=True),
        ),
    ]
