# Generated by Django 3.1 on 2020-09-11 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_auto_20200911_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staging',
            name='Int_Final_Result',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='staging',
            name='Int_HR_Result',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='staging',
            name='Int_P1_Result',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='staging',
            name='Int_p2_Date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='staging',
            name='Int_p2_Result',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='staging',
            name='applicant_code',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='staging',
            name='offer_amt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staging',
            name='preferred_company',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='staging',
            name='preferred_location',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='staging',
            name='reason',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='staging',
            name='remarks',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='staging',
            name='vacancy_code',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='staging',
            name='week_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='staging',
            name='wk_year',
            field=models.IntegerField(null=True),
        ),
    ]
